language: java

dist: xenial

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

env:
  - JAVA_ARG_LINE=""
  - JAVA_ARG_LINE="-Xint"  # Interpreted, i.e. no JIT
  - JAVA_ARG_LINE="-XX:TieredStopAtLevel=3"  # Just C1 not C2

script: mvn test -B -DargLine="$JAVA_ARG_LINE"
